### PR TITLE
Build and CodeQL Updates

### PR DESCRIPTION
**Pull request by collinmcneese**
Signed-off-by: Collin McNeese <collinmcneese@github.com>

- Updates build workflow for #35 to not attempt commit when no changes are present in `dist/`
- Updates CodeQL workflow to trigger when there are `**.js` changes

### CODE REVIEW

**Review by rockin-robinson — APPROVED** [review]
Sweet! Thank you! That was quick! 🥳

**Comment by collinmcneese** [comment]
I updated it a little bit as well to prevent CodeQL scans when there are not any `js` changes.

**Review by rockin-robinson — APPROVED** [review]
Cool beans. Looks good after the updates 👍

**Review by sam1el — APPROVED** [review]
Seems legit.

**Pull request merged**
