### PR TITLE
Add input validation

### PR DESCRIPTION
**Pull request by frye**
This PR adds basic input validation for secrets pulled in during the action run. Strings are checked to exist and not be empty, GUIDs and emails are validated to exist and being right format. And GITHUB_TOKEN presence is checked.

I have tested the changes with several different configurations of secrets in my personal repo.

#8

### CODE REVIEW

**Comment by collinmcneese** [comment]
Rather than adding in a new module for the validation, would something like this work? 

```javascript
// Function to validate data types passed via argument
// Supported types: string, number, array, object, uuid, email
function validate_data_type(data, type) {
  try {
    switch (type) {
      case 'string':
        return typeof data === 'string';
      case 'number':
        return typeof data === 'number';
      case 'array':
        return Array.isArray(data);
      case 'object':
        return typeof data === 'object';
      case 'uuid':
        return typeof data === 'string' && data.length === 36;
      case 'email':
        return typeof data === 'string' && data.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/);
      default:
        return false;
    }
  } catch (error) {
    console.log(error);
    core.setFailed(`Failed to validate data type: expected ${data} to be ${type} \n${error}`);
  }
}
```

**Comment by frye** [comment]
This would definitely work. The way I'm imagining this to move forward with the next version and us picking more information up from the issues / variables, I think there is value in using the module. But I am happy to take a step back if that is preferred at this stage.

**Comment by collinmcneese** [comment]
I don't think having it there is a bad thing, especially if we are going to leverage it more, just wanted to note it!

**Comment by frye** [comment]
Also, I can't merge this myself as I lack permissions. So if this is considered good enough for now someone else needs to merge it in.

**Review by collinmcneese — APPROVED** [review]

**Review by sam1el — APPROVED** [review]
Code looks good.

**Pull request merged**
