### PR TITLE
Edit touchpoint functionality

### PR DESCRIPTION
**Pull request by srvchawla**
Added edit/update touchpoint function to sync edits to a touchpoint from github to totango. 
Functions:
1. Added totango events API url.
2. Updated edited function to parse issue body to extract the touchpoint id populated as html comment.
3. Added Get events: added get_event function to call totango for a touchpoint id and get the event_id back to make the edits call.
4. Edit Touchpoint: edit_touchpoint function to call totango events api and update the edits made in a touchpoint in github to totango. 
5. Added relevant error handling. Parse Int function to force resolve undefined id issue.

Issue Details https://github.com/jmassardo/issues-to-totango/issues/56

### CODE REVIEW

**Review by sam1el — APPROVED** [review]
Code looks good to me. Any chance of a test being written for this?

**Review by rockin-robinson — CHANGES_REQUESTED** [review]
@srvchawla I'm running into some errors while testing this.

Could you please commit the top index.js file, instead of the pre-built index.js that is under the dist/ folder? The build action should create and commit the dist/index.js file for you. 

Thank you!

**Comment by srvchawla** [comment]
Oops! added edited as a type to index.js.

**Review by rockin-robinson — APPROVED** [review]
Tested and it's working. Great job!

**Pull request merged**
